apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: myubuntu
        image: ubuntunew:latest # Mengambil dari local images Anda
        command: ["/bin/sh", "-c", "sleep infinity"]
        ports:
        - containerPort: 22