apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: apache-php
        image: php:8.2-apache
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
          - |
            # 1. Install driver MongoDB
            apt-get update && apt-get install -y libssl-dev && \
            pecl install mongodb && \
            docker-php-ext-enable mongodb;
            
            # 2. Membuat file index.php dengan cara yang lebih aman
            cat <<'EOF' > /var/www/html/index.php
            <?php
            header('Content-Type: text/plain');
            $host = "mongo-service";
            $port = "27017";
            try {
                // Gunakan array option di parameter kedua dengan benar
                $options = ["connectTimeoutMS" => 2000];
                $manager = new MongoDB\Driver\Manager("mongodb://$host:$port", $options);
                $command = new MongoDB\Driver\Command(['listDatabases' => 1]);
                $cursor = $manager->executeCommand('admin', $command);
                echo "Koneksi Berhasil!\n";
                echo "Melayani dari Pod: " . gethostname() . "\n\n";
                echo "Daftar Database:\n";
                foreach ($cursor as $db) {
                    // Coba akses secara langsung (beberapa versi driver)
                    if (isset($db->name)) {
                        echo "- " . $db->name . "\n";
                    } 
                    // Coba akses jika objek dibungkus dalam properti 'databases' (versi terbaru)
                    elseif (isset($db->databases) && is_array($db->databases)) {
                        foreach($db->databases as $database) {
                            echo "- " . $database->name . "\n";
                        }
                    }
                    // Jika masih tidak ketemu, paksa konversi ke array untuk melihat kuncinya
                    else {
                        $dbArray = (array)$db;
                        // MongoDB biasanya mengembalikan nama dalam key 'name'
                        echo "- " . ($dbArray['name'] ?? 'Data ditemukan tapi key tidak cocok') . "\n";
                    }
                }
            } catch (Exception $e) {
                echo "Koneksi Gagal: " . $e->getMessage();
            }
            ?>
            EOF

            # 3. Jalankan Apache
            apache2-foreground
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 80
      
      